index:
    path: /api/v7
    controller: App\Controller\HelpController::index

login:
  path: /api/v7/login
  controller: App\Controller\LoginController::login

allFiles:
  path: /api/v7/files
  controller: App\Controller\FileController::getAll


oneFile:
  path: /api/v7/files/{id}
  controller: App\Controller\FileController::getOne
  methods: [GET, POST]
  schemes: [https, http]
  requirements:
    id: '\d+'

delOneFileById:
  path: /api/v7/files/{id}
  controller: App\Controller\FileController::delOneFileById
  methods: [DELETE]
  schemes: [https, http]
  requirements:
    id: '\d+'

  #defaults: file_id

delOneFileByIdAndType:
  path: /api/v7/files/{id}/{type}
  controller: App\Controller\FileController::delOneFileByIdAndType
  methods: [DELETE]
  schemes: [https, http]
  requirements:
    id: '\d+'
    type: "[a-zA-Z]+"
  #condition: "request.attributes.get('type') in ['student_id','teacher_id'] 
